ARG VERSION=focal
FROM ubuntu:$VERSION
ARG VERSION
EXPOSE 8080 6881

SHELL ["/bin/bash", "-c"]
RUN apt update -y
RUN apt install libssl-dev wget iputils-ping -y

RUN wget http://download.ap.bittorrent.com/track/beta/endpoint/utserver/os/linux-x64-ubuntu-13-04 -O utserver.tar.gz
RUN tar -zxvf utserver.tar.gz -C /opt/
RUN ln -s /opt/utorrent-server-*/utserver /usr/bin/utserver

RUN utserver -settingspath /opt/utorrent-server-*/ &

CMD ping localhost