services:
  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolver.rule=Host(`flaresolver.cbxon.co.uk`)"
      - "traefik.http.routers.flaresolver.entrypoints=web"