services:  
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - TZ=Europe/London
    volumes:
      - /media-stack/conf/jackett:/config
      - /media-stack/data/downloads/torrents:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.cbxon.co.uk`)"
      - "traefik.http.routers.jackett.entrypoints=web"