---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=Europe/London
    volumes:
      - C:\media-stack\conf\heimdall:/config
    ports:
      - 80:80
      - 443:443