---
- hosts: all
  become: true
  vars:
    - stack_location: /opt/stack-config
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0775'
        owner: ansible
        group: docker
      loop:
        - /media/tv
        - /media/movies
        - /media/downloads
        - /media/music
        - '{{ stack_location }}'

    - name: Copy Stack Config files
      ansible.builtin.copy:
        src: ../stack-config/
        dest: '{{ stack_location }}'
        mode: '0775'
        owner: ansible
        group: docker

    - name: Run Docker Compose
      ansible.builtin.shell:
        cmd: docker compose down && docker compose up -d
        chdir: '{{ stack_location }}'
