---
- hosts: all
  become: true
  tasks:
    - name: Install Required System Packages
      ansible.builtin.apt:
        pkg: rclone=1.53.3*
        state: present
        update_cache: true

    - name: Copy Backup Configuration
      ansible.builtin.copy:
        dest: '{{ item.dest }}'
        src: '{{ item.src }}'
        mode: '{{ item.mode }}'
        force: true
      loop:
        - { dest: '/home/ansible/.config/rclone/rclone.conf', src: '../rclone/rclone.conf', mode: "0644" }
        - { dest: '/usr/local/bin/backups.sh', src: './backups.sh', mode: "0755" }

    - name: Configure Backup Cron Job
      ansible.builtin.cron:
        user: ansible
        name: "Backup Docker"
        minute: "0"
        hour: "23"
        job: "backups.sh"
